---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: any-old-app-devl
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  sourceRef:
    kind: GitRepository
    name: any-old-app-main
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: any-old-app-version
